# Stage 1: Build
FROM node:20-alpine as build-stage
WORKDIR /app

# Accept API URL as build argument
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Production
FROM nginx:stable-alpine
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Em produção no Dockerfile geralmente expomos a porta padrão do nginx, 
# mas seu NAS redireciona 3002:3002, então vamos garantir que o nginx ouça na 3002
# se o seu nginx.conf estiver configurado para isso.
EXPOSE 3002
CMD ["nginx", "-g", "daemon off;"]
